on:
    schedule:
        -   cron: '0 3 * * *'
name: Rebuild Docker images
jobs:
    rebuild-master-images:
        name: Rebuild master images on Docker Hub
        runs-on: ubuntu-20.04
        steps:
            -   name: GIT checkout branch - refs/heads/master
                uses: actions/checkout@v2
                with:
                    ref: refs/heads/master
            -   name: Login to Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
            -   name: Generate PHP-FPM tag
                env:
                    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                run: |
                    DOCKER_PHP_FPM_IMAGE_TAG=gitlab-action-`tar -cf - project-base/docker/php-fpm | md5sum | awk '{ print $1 }'`
                    echo "DOCKER_PHP_FPM_IMAGE_TAG=${DOCKER_PHP_FPM_IMAGE_TAG}" >> $GITHUB_ENV
                    echo "DOCKER_PHP_FPM_MASTER_IMAGE_TAG=${DOCKER_PHP_FPM_IMAGE_TAG}" >> $GITHUB_ENV
                    echo "DOCKER_USERNAME=${DOCKER_USERNAME}" >> $GITHUB_ENV
            -   name: Build PHP-FPM image and push it to Docker Hub
                run: sh .github/build-php-fpm-image.sh
            -   name: Generate Elasticseach tag
                run: |
                    DOCKER_ELASTICSEARCH_IMAGE_TAG=gitlab-action-`tar -cf - project-base/docker/elasticsearch | md5sum | awk '{ print $1 }'`
                    echo "DOCKER_ELASTICSEARCH_IMAGE_TAG=${DOCKER_ELASTICSEARCH_IMAGE_TAG}" >> $GITHUB_ENV
                    echo "DOCKER_ELASTICSEARCH_MASTER_IMAGE_TAG=${DOCKER_ELASTICSEARCH_IMAGE_TAG}" >> $GITHUB_ENV
            -   name: Build Elasticsearch image and push it to Docker Hub
                run: sh .github/build-elasticsearch-image.sh
    rebuild-9-1-images:
        name: Rebuild 9.1 images on Docker Hub
        runs-on: ubuntu-20.04
        steps:
            -   name: GIT checkout branch - refs/heads/9.1
                uses: actions/checkout@v2
                with:
                    ref: refs/heads/9.1
            -   name: Login to Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
            -   name: Generate PHP-FPM tag
                env:
                    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                run: |
                    DOCKER_PHP_FPM_9_1_IMAGE_TAG=gitlab-action-`tar -cf - project-base/docker/php-fpm | md5sum | awk '{ print $1 }'`
                    if [[ "$DOCKER_PHP_FPM_9_1_IMAGE_TAG" == "$DOCKER_PHP_FPM_MASTER_IMAGE_TAG" ]]; then
                        DOCKER_PHP_FPM_9_1_TAG_SAME_AS_MASTER = 1
                    else
                        DOCKER_PHP_FPM_9_1_TAG_SAME_AS_MASTER = 0
                    fi
                    echo "DOCKER_PHP_FPM_IMAGE_TAG=${DOCKER_PHP_FPM_9_1_IMAGE_TAG}" >> $GITHUB_ENV
                    echo "DOCKER_PHP_FPM_9_1_TAG_SAME_AS_MASTER=${DOCKER_PHP_FPM_9_1_TAG_SAME_AS_MASTER}" >> $GITHUB_ENV
                    echo "DOCKER_USERNAME=${DOCKER_USERNAME}" >> $GITHUB_ENV
            -   name: Build PHP-FPM image and push it to Docker Hub
                run: sh .github/build-php-fpm-image.sh
                if: env.DOCKER_PHP_FPM_9_1_TAG_SAME_AS_MASTER == 0
            -   name: Generate Elasticseach tag
                run: |
                    DOCKER_ELASTICSEARCH_9_1_IMAGE_TAG=gitlab-action-`tar -cf - project-base/docker/elasticsearch | md5sum | awk '{ print $1 }'`
                    if [[ "DOCKER_ELASTICSEARCH_9_1_IMAGE_TAG" == "$DOCKER_ELASTICSEARCH_MASTER_IMAGE_TAG" ]]; then
                        DOCKER_ELASTICSEARCH_9_1_TAG_SAME_AS_MASTER = 1
                    else
                        DOCKER_ELASTICSEARCH_9_1_TAG_SAME_AS_MASTER = 0
                    fi
                    echo "DOCKER_ELASTICSEARCH_IMAGE_TAG=${DOCKER_ELASTICSEARCH_9_1_IMAGE_TAG}" >> $GITHUB_ENV
                    echo "DOCKER_ELASTICSEARCH_9_1_TAG_SAME_AS_MASTER=${DOCKER_ELASTICSEARCH_9_1_TAG_SAME_AS_MASTER}" >> $GITHUB_ENV
            -   name: Build Elasticsearch image and push it to Docker Hub
                if: env.DOCKER_ELASTICSEARCH_9_1_TAG_SAME_AS_MASTER == 0
                run: sh .github/build-elasticsearch-image.sh
